name: Auto Update Worker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 初始化仓库
        uses: actions/checkout@v4

      - name: 创建Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 安装unzip
        run: |
          sudo apt-get install -y unzip

      - name: 下载最新的BPB worker
        run: |
          rm -rf ./*
          wget -O worker.zip https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/latest/download/worker.zip
          unzip -o worker.zip
          rm worker.zip

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: '自动同步最新 Worker 版本'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
